version: '3'

services:
  minio:
    image: docker.io/minio:latest
    container_name: minio
    volumes:
      - ./minio-data:/minio-data:z
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: 'user'
      MINIO_ROOT_PASSWORD: 'password'
      MINIO_ADDRESS: ':9000'
      MINIO_CONSOLE_ADDRESS: ':9001'
    command: minio server /minio-data
    networks:
      - ta
  redis:
    image: docker.io/redis:alpine
    container_name: redis
    volumes:
      - ./redis-data:/data:z
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password
    networks:
      - ta

networks:
  ta:
    driver: bridge
