services:
  mysql:
    container_name: mysql-db
    image: mysql:8.0.40
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: qwerty123
    userns_mode: "keep-id:uid=1000,gid=1000"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db_data: